//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ThuocService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eThuoc", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eThuoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double donGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string donViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idThuocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenThuocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double donGia {
            get {
                return this.donGiaField;
            }
            set {
                if ((this.donGiaField.Equals(value) != true)) {
                    this.donGiaField = value;
                    this.RaisePropertyChanged("donGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string donVi {
            get {
                return this.donViField;
            }
            set {
                if ((object.ReferenceEquals(this.donViField, value) != true)) {
                    this.donViField = value;
                    this.RaisePropertyChanged("donVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idThuoc {
            get {
                return this.idThuocField;
            }
            set {
                if ((this.idThuocField.Equals(value) != true)) {
                    this.idThuocField = value;
                    this.RaisePropertyChanged("idThuoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moTa {
            get {
                return this.moTaField;
            }
            set {
                if ((object.ReferenceEquals(this.moTaField, value) != true)) {
                    this.moTaField = value;
                    this.RaisePropertyChanged("moTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenThuoc {
            get {
                return this.tenThuocField;
            }
            set {
                if ((object.ReferenceEquals(this.tenThuocField, value) != true)) {
                    this.tenThuocField = value;
                    this.RaisePropertyChanged("tenThuoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThuocService.IThuocWCF")]
    public interface IThuocWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThuocWCF/GetThuocs", ReplyAction="http://tempuri.org/IThuocWCF/GetThuocsResponse")]
        GUI.ThuocService.eThuoc[] GetThuocs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThuocWCF/GetThuocs", ReplyAction="http://tempuri.org/IThuocWCF/GetThuocsResponse")]
        System.Threading.Tasks.Task<GUI.ThuocService.eThuoc[]> GetThuocsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThuocWCF/AddThuoc", ReplyAction="http://tempuri.org/IThuocWCF/AddThuocResponse")]
        int AddThuoc(GUI.ThuocService.eThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThuocWCF/AddThuoc", ReplyAction="http://tempuri.org/IThuocWCF/AddThuocResponse")]
        System.Threading.Tasks.Task<int> AddThuocAsync(GUI.ThuocService.eThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThuocWCF/getThuocbyID", ReplyAction="http://tempuri.org/IThuocWCF/getThuocbyIDResponse")]
        GUI.ThuocService.eThuoc getThuocbyID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThuocWCF/getThuocbyID", ReplyAction="http://tempuri.org/IThuocWCF/getThuocbyIDResponse")]
        System.Threading.Tasks.Task<GUI.ThuocService.eThuoc> getThuocbyIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IThuocWCFChannel : GUI.ThuocService.IThuocWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThuocWCFClient : System.ServiceModel.ClientBase<GUI.ThuocService.IThuocWCF>, GUI.ThuocService.IThuocWCF {
        
        public ThuocWCFClient() {
        }
        
        public ThuocWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThuocWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThuocWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThuocWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GUI.ThuocService.eThuoc[] GetThuocs() {
            return base.Channel.GetThuocs();
        }
        
        public System.Threading.Tasks.Task<GUI.ThuocService.eThuoc[]> GetThuocsAsync() {
            return base.Channel.GetThuocsAsync();
        }
        
        public int AddThuoc(GUI.ThuocService.eThuoc kh) {
            return base.Channel.AddThuoc(kh);
        }
        
        public System.Threading.Tasks.Task<int> AddThuocAsync(GUI.ThuocService.eThuoc kh) {
            return base.Channel.AddThuocAsync(kh);
        }
        
        public GUI.ThuocService.eThuoc getThuocbyID(int id) {
            return base.Channel.getThuocbyID(id);
        }
        
        public System.Threading.Tasks.Task<GUI.ThuocService.eThuoc> getThuocbyIDAsync(int id) {
            return base.Channel.getThuocbyIDAsync(id);
        }
    }
}
