//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.LeTanService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eLeTan", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eLeTan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool gioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soCMNDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soDienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string useNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((this.gioiTinhField.Equals(value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idNV {
            get {
                return this.idNVField;
            }
            set {
                if ((this.idNVField.Equals(value) != true)) {
                    this.idNVField = value;
                    this.RaisePropertyChanged("idNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((this.ngaySinhField.Equals(value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passWord {
            get {
                return this.passWordField;
            }
            set {
                if ((object.ReferenceEquals(this.passWordField, value) != true)) {
                    this.passWordField = value;
                    this.RaisePropertyChanged("passWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soCMND {
            get {
                return this.soCMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.soCMNDField, value) != true)) {
                    this.soCMNDField = value;
                    this.RaisePropertyChanged("soCMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.soDienThoaiField, value) != true)) {
                    this.soDienThoaiField = value;
                    this.RaisePropertyChanged("soDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenNV {
            get {
                return this.tenNVField;
            }
            set {
                if ((object.ReferenceEquals(this.tenNVField, value) != true)) {
                    this.tenNVField = value;
                    this.RaisePropertyChanged("tenNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string useName {
            get {
                return this.useNameField;
            }
            set {
                if ((object.ReferenceEquals(this.useNameField, value) != true)) {
                    this.useNameField = value;
                    this.RaisePropertyChanged("useName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeTanService.ILeTanWCF")]
    public interface ILeTanWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/AddLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/AddLeTanResponse")]
        int AddLeTan(GUI.LeTanService.eLeTan leTan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/AddLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/AddLeTanResponse")]
        System.Threading.Tasks.Task<int> AddLeTanAsync(GUI.LeTanService.eLeTan leTan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/UpdateLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/UpdateLeTanResponse")]
        void UpdateLeTan(GUI.LeTanService.eLeTan leTan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/UpdateLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/UpdateLeTanResponse")]
        System.Threading.Tasks.Task UpdateLeTanAsync(GUI.LeTanService.eLeTan leTan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/RemoveLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/RemoveLeTanResponse")]
        int RemoveLeTan(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/RemoveLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/RemoveLeTanResponse")]
        System.Threading.Tasks.Task<int> RemoveLeTanAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/getAllLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/getAllLeTanResponse")]
        GUI.LeTanService.eLeTan[] getAllLeTan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/getAllLeTan", ReplyAction="http://tempuri.org/ILeTanWCF/getAllLeTanResponse")]
        System.Threading.Tasks.Task<GUI.LeTanService.eLeTan[]> getAllLeTanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/getLeTanByUse", ReplyAction="http://tempuri.org/ILeTanWCF/getLeTanByUseResponse")]
        GUI.LeTanService.eLeTan getLeTanByUse(string id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeTanWCF/getLeTanByUse", ReplyAction="http://tempuri.org/ILeTanWCF/getLeTanByUseResponse")]
        System.Threading.Tasks.Task<GUI.LeTanService.eLeTan> getLeTanByUseAsync(string id, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeTanWCFChannel : GUI.LeTanService.ILeTanWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeTanWCFClient : System.ServiceModel.ClientBase<GUI.LeTanService.ILeTanWCF>, GUI.LeTanService.ILeTanWCF {
        
        public LeTanWCFClient() {
        }
        
        public LeTanWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeTanWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeTanWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeTanWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddLeTan(GUI.LeTanService.eLeTan leTan) {
            return base.Channel.AddLeTan(leTan);
        }
        
        public System.Threading.Tasks.Task<int> AddLeTanAsync(GUI.LeTanService.eLeTan leTan) {
            return base.Channel.AddLeTanAsync(leTan);
        }
        
        public void UpdateLeTan(GUI.LeTanService.eLeTan leTan) {
            base.Channel.UpdateLeTan(leTan);
        }
        
        public System.Threading.Tasks.Task UpdateLeTanAsync(GUI.LeTanService.eLeTan leTan) {
            return base.Channel.UpdateLeTanAsync(leTan);
        }
        
        public int RemoveLeTan(int id) {
            return base.Channel.RemoveLeTan(id);
        }
        
        public System.Threading.Tasks.Task<int> RemoveLeTanAsync(int id) {
            return base.Channel.RemoveLeTanAsync(id);
        }
        
        public GUI.LeTanService.eLeTan[] getAllLeTan() {
            return base.Channel.getAllLeTan();
        }
        
        public System.Threading.Tasks.Task<GUI.LeTanService.eLeTan[]> getAllLeTanAsync() {
            return base.Channel.getAllLeTanAsync();
        }
        
        public GUI.LeTanService.eLeTan getLeTanByUse(string id, string pass) {
            return base.Channel.getLeTanByUse(id, pass);
        }
        
        public System.Threading.Tasks.Task<GUI.LeTanService.eLeTan> getLeTanByUseAsync(string id, string pass) {
            return base.Channel.getLeTanByUseAsync(id, pass);
        }
    }
}
