//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.PhieuKhamService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ePhieuKham", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class ePhieuKham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPhieuKhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngayDKKhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string truyenMaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idKH {
            get {
                return this.idKHField;
            }
            set {
                if ((this.idKHField.Equals(value) != true)) {
                    this.idKHField = value;
                    this.RaisePropertyChanged("idKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idNV {
            get {
                return this.idNVField;
            }
            set {
                if ((this.idNVField.Equals(value) != true)) {
                    this.idNVField = value;
                    this.RaisePropertyChanged("idNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPhieuKham {
            get {
                return this.idPhieuKhamField;
            }
            set {
                if ((this.idPhieuKhamField.Equals(value) != true)) {
                    this.idPhieuKhamField = value;
                    this.RaisePropertyChanged("idPhieuKham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moTa {
            get {
                return this.moTaField;
            }
            set {
                if ((object.ReferenceEquals(this.moTaField, value) != true)) {
                    this.moTaField = value;
                    this.RaisePropertyChanged("moTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngayDKKham {
            get {
                return this.ngayDKKhamField;
            }
            set {
                if ((this.ngayDKKhamField.Equals(value) != true)) {
                    this.ngayDKKhamField = value;
                    this.RaisePropertyChanged("ngayDKKham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                if ((this.tinhTrangField.Equals(value) != true)) {
                    this.tinhTrangField = value;
                    this.RaisePropertyChanged("tinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string truyenMa {
            get {
                return this.truyenMaField;
            }
            set {
                if ((object.ReferenceEquals(this.truyenMaField, value) != true)) {
                    this.truyenMaField = value;
                    this.RaisePropertyChanged("truyenMa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhieuKhamService.IPhieuKhamWCF")]
    public interface IPhieuKhamWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_theoNgay", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_theoNgayResponse")]
        GUI.PhieuKhamService.ePhieuKham[] getPhieuKham_theoNgay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_theoNgay", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_theoNgayResponse")]
        System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuKham_theoNgayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuhen", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuhenResponse")]
        GUI.PhieuKhamService.ePhieuKham[] getPhieuhen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuhen", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuhenResponse")]
        System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuhenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TrongNgay", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TrongNgayResponse")]
        GUI.PhieuKhamService.ePhieuKham[] getPhieuhen_TrongNgay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TrongNgay", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TrongNgayResponse")]
        System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuhen_TrongNgayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TimKiem", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TimKiemResponse")]
        GUI.PhieuKhamService.ePhieuKham[] getPhieuhen_TimKiem(System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TimKiem", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuhen_TimKiemResponse")]
        System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuhen_TimKiemAsync(System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/AddPhieuKham", ReplyAction="http://tempuri.org/IPhieuKhamWCF/AddPhieuKhamResponse")]
        int AddPhieuKham(GUI.PhieuKhamService.ePhieuKham epk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/AddPhieuKham", ReplyAction="http://tempuri.org/IPhieuKhamWCF/AddPhieuKhamResponse")]
        System.Threading.Tasks.Task<int> AddPhieuKhamAsync(GUI.PhieuKhamService.ePhieuKham epk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/UpdatePhieuKham", ReplyAction="http://tempuri.org/IPhieuKhamWCF/UpdatePhieuKhamResponse")]
        void UpdatePhieuKham(GUI.PhieuKhamService.ePhieuKham epk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/UpdatePhieuKham", ReplyAction="http://tempuri.org/IPhieuKhamWCF/UpdatePhieuKhamResponse")]
        System.Threading.Tasks.Task UpdatePhieuKhamAsync(GUI.PhieuKhamService.ePhieuKham epk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/UpdateTinhTrang_PhieuKham", ReplyAction="http://tempuri.org/IPhieuKhamWCF/UpdateTinhTrang_PhieuKhamResponse")]
        int UpdateTinhTrang_PhieuKham(GUI.PhieuKhamService.ePhieuKham epk, int tinhtrangnew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/UpdateTinhTrang_PhieuKham", ReplyAction="http://tempuri.org/IPhieuKhamWCF/UpdateTinhTrang_PhieuKhamResponse")]
        System.Threading.Tasks.Task<int> UpdateTinhTrang_PhieuKhamAsync(GUI.PhieuKhamService.ePhieuKham epk, int tinhtrangnew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_byID", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_byIDResponse")]
        GUI.PhieuKhamService.ePhieuKham getPhieuKham_byID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_byID", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getPhieuKham_byIDResponse")]
        System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham> getPhieuKham_byIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getIdLast", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getIdLastResponse")]
        int getIdLast();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuKhamWCF/getIdLast", ReplyAction="http://tempuri.org/IPhieuKhamWCF/getIdLastResponse")]
        System.Threading.Tasks.Task<int> getIdLastAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhieuKhamWCFChannel : GUI.PhieuKhamService.IPhieuKhamWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhieuKhamWCFClient : System.ServiceModel.ClientBase<GUI.PhieuKhamService.IPhieuKhamWCF>, GUI.PhieuKhamService.IPhieuKhamWCF {
        
        public PhieuKhamWCFClient() {
        }
        
        public PhieuKhamWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhieuKhamWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuKhamWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuKhamWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GUI.PhieuKhamService.ePhieuKham[] getPhieuKham_theoNgay() {
            return base.Channel.getPhieuKham_theoNgay();
        }
        
        public System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuKham_theoNgayAsync() {
            return base.Channel.getPhieuKham_theoNgayAsync();
        }
        
        public GUI.PhieuKhamService.ePhieuKham[] getPhieuhen() {
            return base.Channel.getPhieuhen();
        }
        
        public System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuhenAsync() {
            return base.Channel.getPhieuhenAsync();
        }
        
        public GUI.PhieuKhamService.ePhieuKham[] getPhieuhen_TrongNgay() {
            return base.Channel.getPhieuhen_TrongNgay();
        }
        
        public System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuhen_TrongNgayAsync() {
            return base.Channel.getPhieuhen_TrongNgayAsync();
        }
        
        public GUI.PhieuKhamService.ePhieuKham[] getPhieuhen_TimKiem(System.DateTime from, System.DateTime to) {
            return base.Channel.getPhieuhen_TimKiem(from, to);
        }
        
        public System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham[]> getPhieuhen_TimKiemAsync(System.DateTime from, System.DateTime to) {
            return base.Channel.getPhieuhen_TimKiemAsync(from, to);
        }
        
        public int AddPhieuKham(GUI.PhieuKhamService.ePhieuKham epk) {
            return base.Channel.AddPhieuKham(epk);
        }
        
        public System.Threading.Tasks.Task<int> AddPhieuKhamAsync(GUI.PhieuKhamService.ePhieuKham epk) {
            return base.Channel.AddPhieuKhamAsync(epk);
        }
        
        public void UpdatePhieuKham(GUI.PhieuKhamService.ePhieuKham epk) {
            base.Channel.UpdatePhieuKham(epk);
        }
        
        public System.Threading.Tasks.Task UpdatePhieuKhamAsync(GUI.PhieuKhamService.ePhieuKham epk) {
            return base.Channel.UpdatePhieuKhamAsync(epk);
        }
        
        public int UpdateTinhTrang_PhieuKham(GUI.PhieuKhamService.ePhieuKham epk, int tinhtrangnew) {
            return base.Channel.UpdateTinhTrang_PhieuKham(epk, tinhtrangnew);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTinhTrang_PhieuKhamAsync(GUI.PhieuKhamService.ePhieuKham epk, int tinhtrangnew) {
            return base.Channel.UpdateTinhTrang_PhieuKhamAsync(epk, tinhtrangnew);
        }
        
        public GUI.PhieuKhamService.ePhieuKham getPhieuKham_byID(int id) {
            return base.Channel.getPhieuKham_byID(id);
        }
        
        public System.Threading.Tasks.Task<GUI.PhieuKhamService.ePhieuKham> getPhieuKham_byIDAsync(int id) {
            return base.Channel.getPhieuKham_byIDAsync(id);
        }
        
        public int getIdLast() {
            return base.Channel.getIdLast();
        }
        
        public System.Threading.Tasks.Task<int> getIdLastAsync() {
            return base.Channel.getIdLastAsync();
        }
    }
}
