//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.DonThuocService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eDonThuoc", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eDonThuoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDonThuocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idNhaSiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPhieuKhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string momField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngayLapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool tinhTrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDonThuoc {
            get {
                return this.idDonThuocField;
            }
            set {
                if ((this.idDonThuocField.Equals(value) != true)) {
                    this.idDonThuocField = value;
                    this.RaisePropertyChanged("idDonThuoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idNhaSi {
            get {
                return this.idNhaSiField;
            }
            set {
                if ((this.idNhaSiField.Equals(value) != true)) {
                    this.idNhaSiField = value;
                    this.RaisePropertyChanged("idNhaSi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPhieuKham {
            get {
                return this.idPhieuKhamField;
            }
            set {
                if ((this.idPhieuKhamField.Equals(value) != true)) {
                    this.idPhieuKhamField = value;
                    this.RaisePropertyChanged("idPhieuKham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mom {
            get {
                return this.momField;
            }
            set {
                if ((object.ReferenceEquals(this.momField, value) != true)) {
                    this.momField = value;
                    this.RaisePropertyChanged("mom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngayLap {
            get {
                return this.ngayLapField;
            }
            set {
                if ((this.ngayLapField.Equals(value) != true)) {
                    this.ngayLapField = value;
                    this.RaisePropertyChanged("ngayLap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool tinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                if ((this.tinhTrangField.Equals(value) != true)) {
                    this.tinhTrangField = value;
                    this.RaisePropertyChanged("tinhTrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DonThuocService.IDonThuocWCF")]
    public interface IDonThuocWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/GetDonThuocs", ReplyAction="http://tempuri.org/IDonThuocWCF/GetDonThuocsResponse")]
        GUI.DonThuocService.eDonThuoc[] GetDonThuocs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/GetDonThuocs", ReplyAction="http://tempuri.org/IDonThuocWCF/GetDonThuocsResponse")]
        System.Threading.Tasks.Task<GUI.DonThuocService.eDonThuoc[]> GetDonThuocsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/AddDonThuoc", ReplyAction="http://tempuri.org/IDonThuocWCF/AddDonThuocResponse")]
        int AddDonThuoc(GUI.DonThuocService.eDonThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/AddDonThuoc", ReplyAction="http://tempuri.org/IDonThuocWCF/AddDonThuocResponse")]
        System.Threading.Tasks.Task<int> AddDonThuocAsync(GUI.DonThuocService.eDonThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/UpdateDonThuoc", ReplyAction="http://tempuri.org/IDonThuocWCF/UpdateDonThuocResponse")]
        int UpdateDonThuoc(GUI.DonThuocService.eDonThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/UpdateDonThuoc", ReplyAction="http://tempuri.org/IDonThuocWCF/UpdateDonThuocResponse")]
        System.Threading.Tasks.Task<int> UpdateDonThuocAsync(GUI.DonThuocService.eDonThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/getIdLast", ReplyAction="http://tempuri.org/IDonThuocWCF/getIdLastResponse")]
        int getIdLast();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonThuocWCF/getIdLast", ReplyAction="http://tempuri.org/IDonThuocWCF/getIdLastResponse")]
        System.Threading.Tasks.Task<int> getIdLastAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDonThuocWCFChannel : GUI.DonThuocService.IDonThuocWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DonThuocWCFClient : System.ServiceModel.ClientBase<GUI.DonThuocService.IDonThuocWCF>, GUI.DonThuocService.IDonThuocWCF {
        
        public DonThuocWCFClient() {
        }
        
        public DonThuocWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DonThuocWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonThuocWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonThuocWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GUI.DonThuocService.eDonThuoc[] GetDonThuocs() {
            return base.Channel.GetDonThuocs();
        }
        
        public System.Threading.Tasks.Task<GUI.DonThuocService.eDonThuoc[]> GetDonThuocsAsync() {
            return base.Channel.GetDonThuocsAsync();
        }
        
        public int AddDonThuoc(GUI.DonThuocService.eDonThuoc kh) {
            return base.Channel.AddDonThuoc(kh);
        }
        
        public System.Threading.Tasks.Task<int> AddDonThuocAsync(GUI.DonThuocService.eDonThuoc kh) {
            return base.Channel.AddDonThuocAsync(kh);
        }
        
        public int UpdateDonThuoc(GUI.DonThuocService.eDonThuoc kh) {
            return base.Channel.UpdateDonThuoc(kh);
        }
        
        public System.Threading.Tasks.Task<int> UpdateDonThuocAsync(GUI.DonThuocService.eDonThuoc kh) {
            return base.Channel.UpdateDonThuocAsync(kh);
        }
        
        public int getIdLast() {
            return base.Channel.getIdLast();
        }
        
        public System.Threading.Tasks.Task<int> getIdLastAsync() {
            return base.Channel.getIdLastAsync();
        }
    }
}
