//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.DichVuService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eDichVuPhongKham", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eDichVuPhongKham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double donGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenDVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double donGia {
            get {
                return this.donGiaField;
            }
            set {
                if ((this.donGiaField.Equals(value) != true)) {
                    this.donGiaField = value;
                    this.RaisePropertyChanged("donGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDV {
            get {
                return this.idDVField;
            }
            set {
                if ((this.idDVField.Equals(value) != true)) {
                    this.idDVField = value;
                    this.RaisePropertyChanged("idDV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenDV {
            get {
                return this.tenDVField;
            }
            set {
                if ((object.ReferenceEquals(this.tenDVField, value) != true)) {
                    this.tenDVField = value;
                    this.RaisePropertyChanged("tenDV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DichVuService.IDichVuWCF")]
    public interface IDichVuWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/AddDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/AddDichVuResponse")]
        int AddDichVu(GUI.DichVuService.eDichVuPhongKham dv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/AddDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/AddDichVuResponse")]
        System.Threading.Tasks.Task<int> AddDichVuAsync(GUI.DichVuService.eDichVuPhongKham dv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/UpdateDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/UpdateDichVuResponse")]
        void UpdateDichVu(GUI.DichVuService.eDichVuPhongKham dv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/UpdateDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/UpdateDichVuResponse")]
        System.Threading.Tasks.Task UpdateDichVuAsync(GUI.DichVuService.eDichVuPhongKham dv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/RemoveDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/RemoveDichVuResponse")]
        int RemoveDichVu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/RemoveDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/RemoveDichVuResponse")]
        System.Threading.Tasks.Task<int> RemoveDichVuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/GetDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/GetDichVuResponse")]
        GUI.DichVuService.eDichVuPhongKham[] GetDichVu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/GetDichVu", ReplyAction="http://tempuri.org/IDichVuWCF/GetDichVuResponse")]
        System.Threading.Tasks.Task<GUI.DichVuService.eDichVuPhongKham[]> GetDichVuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/getDVbyID", ReplyAction="http://tempuri.org/IDichVuWCF/getDVbyIDResponse")]
        GUI.DichVuService.eDichVuPhongKham getDVbyID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVuWCF/getDVbyID", ReplyAction="http://tempuri.org/IDichVuWCF/getDVbyIDResponse")]
        System.Threading.Tasks.Task<GUI.DichVuService.eDichVuPhongKham> getDVbyIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDichVuWCFChannel : GUI.DichVuService.IDichVuWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DichVuWCFClient : System.ServiceModel.ClientBase<GUI.DichVuService.IDichVuWCF>, GUI.DichVuService.IDichVuWCF {
        
        public DichVuWCFClient() {
        }
        
        public DichVuWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DichVuWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVuWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVuWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddDichVu(GUI.DichVuService.eDichVuPhongKham dv) {
            return base.Channel.AddDichVu(dv);
        }
        
        public System.Threading.Tasks.Task<int> AddDichVuAsync(GUI.DichVuService.eDichVuPhongKham dv) {
            return base.Channel.AddDichVuAsync(dv);
        }
        
        public void UpdateDichVu(GUI.DichVuService.eDichVuPhongKham dv) {
            base.Channel.UpdateDichVu(dv);
        }
        
        public System.Threading.Tasks.Task UpdateDichVuAsync(GUI.DichVuService.eDichVuPhongKham dv) {
            return base.Channel.UpdateDichVuAsync(dv);
        }
        
        public int RemoveDichVu(int id) {
            return base.Channel.RemoveDichVu(id);
        }
        
        public System.Threading.Tasks.Task<int> RemoveDichVuAsync(int id) {
            return base.Channel.RemoveDichVuAsync(id);
        }
        
        public GUI.DichVuService.eDichVuPhongKham[] GetDichVu() {
            return base.Channel.GetDichVu();
        }
        
        public System.Threading.Tasks.Task<GUI.DichVuService.eDichVuPhongKham[]> GetDichVuAsync() {
            return base.Channel.GetDichVuAsync();
        }
        
        public GUI.DichVuService.eDichVuPhongKham getDVbyID(int id) {
            return base.Channel.getDVbyID(id);
        }
        
        public System.Threading.Tasks.Task<GUI.DichVuService.eDichVuPhongKham> getDVbyIDAsync(int id) {
            return base.Channel.getDVbyIDAsync(id);
        }
    }
}
