//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.NhaSiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eNhaSi", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eNhaSi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool gioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idNhaSiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soCMNDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soDienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenNhaSiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string useNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((this.gioiTinhField.Equals(value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idNhaSi {
            get {
                return this.idNhaSiField;
            }
            set {
                if ((this.idNhaSiField.Equals(value) != true)) {
                    this.idNhaSiField = value;
                    this.RaisePropertyChanged("idNhaSi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((this.ngaySinhField.Equals(value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passWord {
            get {
                return this.passWordField;
            }
            set {
                if ((object.ReferenceEquals(this.passWordField, value) != true)) {
                    this.passWordField = value;
                    this.RaisePropertyChanged("passWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soCMND {
            get {
                return this.soCMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.soCMNDField, value) != true)) {
                    this.soCMNDField = value;
                    this.RaisePropertyChanged("soCMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.soDienThoaiField, value) != true)) {
                    this.soDienThoaiField = value;
                    this.RaisePropertyChanged("soDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenNhaSi {
            get {
                return this.tenNhaSiField;
            }
            set {
                if ((object.ReferenceEquals(this.tenNhaSiField, value) != true)) {
                    this.tenNhaSiField = value;
                    this.RaisePropertyChanged("tenNhaSi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string useName {
            get {
                return this.useNameField;
            }
            set {
                if ((object.ReferenceEquals(this.useNameField, value) != true)) {
                    this.useNameField = value;
                    this.RaisePropertyChanged("useName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NhaSiService.INhaSiWCF")]
    public interface INhaSiWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/AddNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/AddNhaSiResponse")]
        int AddNhaSi(GUI.NhaSiService.eNhaSi nhaSi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/AddNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/AddNhaSiResponse")]
        System.Threading.Tasks.Task<int> AddNhaSiAsync(GUI.NhaSiService.eNhaSi nhaSi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/UpdateNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/UpdateNhaSiResponse")]
        void UpdateNhaSi(GUI.NhaSiService.eNhaSi nhaSi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/UpdateNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/UpdateNhaSiResponse")]
        System.Threading.Tasks.Task UpdateNhaSiAsync(GUI.NhaSiService.eNhaSi nhaSi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/RemoveNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/RemoveNhaSiResponse")]
        int RemoveNhaSi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/RemoveNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/RemoveNhaSiResponse")]
        System.Threading.Tasks.Task<int> RemoveNhaSiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/getAllNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/getAllNhaSiResponse")]
        GUI.NhaSiService.eNhaSi[] getAllNhaSi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/getAllNhaSi", ReplyAction="http://tempuri.org/INhaSiWCF/getAllNhaSiResponse")]
        System.Threading.Tasks.Task<GUI.NhaSiService.eNhaSi[]> getAllNhaSiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/getNhaSiByUseName", ReplyAction="http://tempuri.org/INhaSiWCF/getNhaSiByUseNameResponse")]
        GUI.NhaSiService.eNhaSi getNhaSiByUseName(string use, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/getNhaSiByUseName", ReplyAction="http://tempuri.org/INhaSiWCF/getNhaSiByUseNameResponse")]
        System.Threading.Tasks.Task<GUI.NhaSiService.eNhaSi> getNhaSiByUseNameAsync(string use, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/getNhabyID", ReplyAction="http://tempuri.org/INhaSiWCF/getNhabyIDResponse")]
        GUI.NhaSiService.eNhaSi getNhabyID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSiWCF/getNhabyID", ReplyAction="http://tempuri.org/INhaSiWCF/getNhabyIDResponse")]
        System.Threading.Tasks.Task<GUI.NhaSiService.eNhaSi> getNhabyIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INhaSiWCFChannel : GUI.NhaSiService.INhaSiWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NhaSiWCFClient : System.ServiceModel.ClientBase<GUI.NhaSiService.INhaSiWCF>, GUI.NhaSiService.INhaSiWCF {
        
        public NhaSiWCFClient() {
        }
        
        public NhaSiWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NhaSiWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhaSiWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhaSiWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddNhaSi(GUI.NhaSiService.eNhaSi nhaSi) {
            return base.Channel.AddNhaSi(nhaSi);
        }
        
        public System.Threading.Tasks.Task<int> AddNhaSiAsync(GUI.NhaSiService.eNhaSi nhaSi) {
            return base.Channel.AddNhaSiAsync(nhaSi);
        }
        
        public void UpdateNhaSi(GUI.NhaSiService.eNhaSi nhaSi) {
            base.Channel.UpdateNhaSi(nhaSi);
        }
        
        public System.Threading.Tasks.Task UpdateNhaSiAsync(GUI.NhaSiService.eNhaSi nhaSi) {
            return base.Channel.UpdateNhaSiAsync(nhaSi);
        }
        
        public int RemoveNhaSi(int id) {
            return base.Channel.RemoveNhaSi(id);
        }
        
        public System.Threading.Tasks.Task<int> RemoveNhaSiAsync(int id) {
            return base.Channel.RemoveNhaSiAsync(id);
        }
        
        public GUI.NhaSiService.eNhaSi[] getAllNhaSi() {
            return base.Channel.getAllNhaSi();
        }
        
        public System.Threading.Tasks.Task<GUI.NhaSiService.eNhaSi[]> getAllNhaSiAsync() {
            return base.Channel.getAllNhaSiAsync();
        }
        
        public GUI.NhaSiService.eNhaSi getNhaSiByUseName(string use, string pass) {
            return base.Channel.getNhaSiByUseName(use, pass);
        }
        
        public System.Threading.Tasks.Task<GUI.NhaSiService.eNhaSi> getNhaSiByUseNameAsync(string use, string pass) {
            return base.Channel.getNhaSiByUseNameAsync(use, pass);
        }
        
        public GUI.NhaSiService.eNhaSi getNhabyID(int id) {
            return base.Channel.getNhabyID(id);
        }
        
        public System.Threading.Tasks.Task<GUI.NhaSiService.eNhaSi> getNhabyIDAsync(int id) {
            return base.Channel.getNhabyIDAsync(id);
        }
    }
}
