//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ChiTietDonThuocService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eChiTietDonThuoc", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eChiTietDonThuoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDonThuocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idThuocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDV {
            get {
                return this.idDVField;
            }
            set {
                if ((this.idDVField.Equals(value) != true)) {
                    this.idDVField = value;
                    this.RaisePropertyChanged("idDV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDonThuoc {
            get {
                return this.idDonThuocField;
            }
            set {
                if ((this.idDonThuocField.Equals(value) != true)) {
                    this.idDonThuocField = value;
                    this.RaisePropertyChanged("idDonThuoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idThuoc {
            get {
                return this.idThuocField;
            }
            set {
                if ((this.idThuocField.Equals(value) != true)) {
                    this.idThuocField = value;
                    this.RaisePropertyChanged("idThuoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soLuong {
            get {
                return this.soLuongField;
            }
            set {
                if ((this.soLuongField.Equals(value) != true)) {
                    this.soLuongField = value;
                    this.RaisePropertyChanged("soLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChiTietDonThuocService.IChiTietDonThuocWCF")]
    public interface IChiTietDonThuocWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietDonThuocWCF/GetChiTietDonThuocs", ReplyAction="http://tempuri.org/IChiTietDonThuocWCF/GetChiTietDonThuocsResponse")]
        GUI.ChiTietDonThuocService.eChiTietDonThuoc[] GetChiTietDonThuocs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietDonThuocWCF/GetChiTietDonThuocs", ReplyAction="http://tempuri.org/IChiTietDonThuocWCF/GetChiTietDonThuocsResponse")]
        System.Threading.Tasks.Task<GUI.ChiTietDonThuocService.eChiTietDonThuoc[]> GetChiTietDonThuocsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietDonThuocWCF/AddChiTietDonThuoc", ReplyAction="http://tempuri.org/IChiTietDonThuocWCF/AddChiTietDonThuocResponse")]
        int AddChiTietDonThuoc(GUI.ChiTietDonThuocService.eChiTietDonThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietDonThuocWCF/AddChiTietDonThuoc", ReplyAction="http://tempuri.org/IChiTietDonThuocWCF/AddChiTietDonThuocResponse")]
        System.Threading.Tasks.Task<int> AddChiTietDonThuocAsync(GUI.ChiTietDonThuocService.eChiTietDonThuoc kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietDonThuocWCF/getChiTietDonThuocbyID", ReplyAction="http://tempuri.org/IChiTietDonThuocWCF/getChiTietDonThuocbyIDResponse")]
        GUI.ChiTietDonThuocService.eChiTietDonThuoc[] getChiTietDonThuocbyID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietDonThuocWCF/getChiTietDonThuocbyID", ReplyAction="http://tempuri.org/IChiTietDonThuocWCF/getChiTietDonThuocbyIDResponse")]
        System.Threading.Tasks.Task<GUI.ChiTietDonThuocService.eChiTietDonThuoc[]> getChiTietDonThuocbyIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChiTietDonThuocWCFChannel : GUI.ChiTietDonThuocService.IChiTietDonThuocWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChiTietDonThuocWCFClient : System.ServiceModel.ClientBase<GUI.ChiTietDonThuocService.IChiTietDonThuocWCF>, GUI.ChiTietDonThuocService.IChiTietDonThuocWCF {
        
        public ChiTietDonThuocWCFClient() {
        }
        
        public ChiTietDonThuocWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChiTietDonThuocWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTietDonThuocWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTietDonThuocWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GUI.ChiTietDonThuocService.eChiTietDonThuoc[] GetChiTietDonThuocs() {
            return base.Channel.GetChiTietDonThuocs();
        }
        
        public System.Threading.Tasks.Task<GUI.ChiTietDonThuocService.eChiTietDonThuoc[]> GetChiTietDonThuocsAsync() {
            return base.Channel.GetChiTietDonThuocsAsync();
        }
        
        public int AddChiTietDonThuoc(GUI.ChiTietDonThuocService.eChiTietDonThuoc kh) {
            return base.Channel.AddChiTietDonThuoc(kh);
        }
        
        public System.Threading.Tasks.Task<int> AddChiTietDonThuocAsync(GUI.ChiTietDonThuocService.eChiTietDonThuoc kh) {
            return base.Channel.AddChiTietDonThuocAsync(kh);
        }
        
        public GUI.ChiTietDonThuocService.eChiTietDonThuoc[] getChiTietDonThuocbyID(int id) {
            return base.Channel.getChiTietDonThuocbyID(id);
        }
        
        public System.Threading.Tasks.Task<GUI.ChiTietDonThuocService.eChiTietDonThuoc[]> getChiTietDonThuocbyIDAsync(int id) {
            return base.Channel.getChiTietDonThuocbyIDAsync(id);
        }
    }
}
